spring:
  application:
    name: techx-api
  datasource:
    url: jdbc:mysql://localhost:3306/techx_nlu
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace

# SWAGGER - http://localhost:8080/swagger-ui/index.html
open-api:
  service:
    api-docs: API documents
    title: techx
    version: v1.0.0
    server: http://localhost:8080
